In [5]:
#Write a function so that the columns of the output matrix are powers of the input vector.
#The order of the powers is determined by the increasing boolean argument. Specifically, whenincreasing is False, the i-th output column is the input vector raised element-wise to the power
#of N - i - 1.
import numpy as np
def Alexandre(array1,n,increasing):
    if increasing==False:
        list1=np.array([x**(n-1-i) for x in array1 for i in range(n) ]).reshape(array1.size,n)
        return list1
    elif increasing==True:
        list3=np.array([x**(i) for x in array1 for i in range(n) ]).reshape(array1.size,n)
        return list3
list1=[int(x) for x in input("enter the elemnts of array:").split()]
array1 = np.array(list1)
no_colum = int(input("enter number of columns:"))
a= Alexandre(array1,no_colum,False)
b= Alexandre(array1,no_colum,True)

print("The input array is:",array1)
print("Number of columns in output matrix should be:",no_colum,)
print("Vander matrix of the input array in decreasing order of powers:\n\n",a,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",b,"\n")

enter the elemnts of array:1 2 3 4 5
enter number of columns:3
The input array is: [1 2 3 4 5]
Number of columns in output matrix should be: 3
Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 



In [21]:
#Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
def movavg(list1,k):
    cumsum=[0]
    moving_avg=[]
    for i, j in enumerate(mylist, 1):
        cumsum.append(cumsum[i-1] + x)
        if i>=k:
            moving_avg1=float((cumsum[i]-cumsum[i-k])/k)
            moving_avg.append(moving_avg1)
        print("Moving average values given in list: ", moving_avg)
        print("Length of the list n-k+1: ", len(moving_avg))
list1=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k=int(input("enter the length of window:"))
mov_avg_val(list1,k)

enter the length of window:3
Moving average values list:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the list l-N+1:  11
